version: '2'
services:
    gateway-app-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/gateway-app/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=gateway-app
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
